[phases.setup]
nixPkgs = ["chromium", "chromedriver", "glibc"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "chromium --version || true"
]

[start]
cmd = "python bot.py"